# Code in this file originally from the mjmech project: https://github.com/mjbots/mjmech
#
# Copyright 2014-2015 Josh Pieper, jjp@pobox.com.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Additional modifications:
#
# Copyright 2016 Sam Creasey, sammy@sammy.net.  All rights reserved.

Import('canonenv')
env = canonenv.Clone()

UI_FILES = [
    'course_map_dialog.ui',
    'sync_dialog.ui',
    'sync_widget.ui',
    'tplot_main_window.ui',
    ]

for filename in UI_FILES:
    output_name = "ui_" + filename.split('.')[0] + ".py"
    env.Command(output_name, File(filename),
                'pyside-uic $SOURCE -o $TARGET')
